name: marshalx
description: Marshal App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  aftarobotlibrary4:
    path: ../../aftarobotlibrary4/aftarobotlibrary4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/icons8-bus-24.png
    - assets/icons8-bus-48.png
    - assets/icons8-bus-96.png

